# Generated by Django 3.0.7 on 2020-06-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='mail',
            field=models.CharField(max_length=50),
        ),
    ]
