# Generated by Django 3.0.7 on 2020-06-24 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0002_auto_20200622_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tngproducts',
            name='label',
            field=models.CharField(choices=[('P', 'BESTSELLER'), ('D', 'NEW')], default='D', max_length=1),
        ),
    ]
