# Generated by Django 3.0.7 on 2020-06-24 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0003_auto_20200624_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tngproducts',
            name='label',
            field=models.CharField(choices=[('P', 'BESTSELLER'), ('D', 'NEW')], max_length=1),
        ),
    ]
