# Generated by Django 3.0.7 on 2020-06-24 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0005_auto_20200624_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tngproducts',
            name='category',
            field=models.CharField(choices=[('A', 'All'), ('MA', 'Mobile Accessories'), ('DA', 'Device Accessories'), ('CS', 'Cool Stuffs')], default='A', max_length=2),
        ),
    ]
