# Generated by Django 3.0.7 on 2020-06-25 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0007_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
