# Generated by Django 3.0.7 on 2020-06-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0009_tngproducts_additional_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tngproducts',
            name='category',
            field=models.CharField(choices=[('A', 'All'), ('MA', 'Mobile Accessories'), ('DA', 'Device Accessories'), ('CS', 'Cool Stuffs'), ('MR', 'Mobile Repair'), ('LR', 'Laptop/Computer Repair'), ('TR', 'iPad/Tablet Repair')], default='A', max_length=2),
        ),
    ]
