# Generated by Django 3.0.7 on 2020-07-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0011_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='addr_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
