# Generated by Django 3.0.7 on 2020-07-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0012_address_addr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('brand', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=10)),
                ('device_type', models.CharField(max_length=50)),
                ('device_model', models.CharField(max_length=50)),
                ('repair_type', models.CharField(max_length=50)),
            ],
        ),
    ]
