# Generated by Django 3.0.7 on 2020-08-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0018_auto_20200817_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinebooking',
            name='time',
            field=models.CharField(default='11:00 to 12:00', max_length=20),
        ),
    ]
