# Generated by Django 3.0.7 on 2020-08-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0021_auto_20200818_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tngproducts',
            name='category',
            field=models.CharField(choices=[('MA', 'Mobile Accessories'), ('LA', 'Laptop Accessories'), ('TA', 'Tablet Accessories'), ('EG', 'Electronic Gadgets'), ('NA', 'Latest Accessories'), ('MR', 'Mobile Repair'), ('LR', 'Laptop/Computer Repair'), ('TR', 'iPad/Tablet Repair')], default='A', max_length=2),
        ),
    ]
