# Generated by Django 3.0.7 on 2020-08-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0022_auto_20200820_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tngproducts',
            name='image',
            field=models.ImageField(upload_to='product_pics'),
        ),
    ]
