# Generated by Django 3.0.7 on 2020-08-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0024_auto_20200826_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tngproducts',
            name='slug',
            field=models.SlugField(default='4hxk2j'),
        ),
    ]
