# Generated by Django 3.0.7 on 2020-08-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0025_auto_20200826_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tngproducts',
            name='slug',
            field=models.SlugField(default='ylsnl3'),
        ),
    ]
