# Generated by Django 3.0.7 on 2020-08-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0027_auto_20200827_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tngproducts',
            name='slug',
            field=models.SlugField(default='tkr2c2'),
        ),
    ]
