# Generated by Django 3.0.7 on 2020-08-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0028_auto_20200827_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tngproducts',
            name='slug',
            field=models.SlugField(db_index=False),
        ),
        migrations.AlterUniqueTogether(
            name='tngproducts',
            unique_together={('slug', 'subcategory')},
        ),
    ]
