# Generated by Django 3.0.7 on 2020-08-27 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0029_auto_20200827_1946'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tngproducts',
            unique_together={('slug', 'category')},
        ),
    ]
