# Generated by Django 3.0.7 on 2020-08-27 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0031_auto_20200827_1955'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tngproducts',
            unique_together=set(),
        ),
    ]
