# Generated by Django 3.0.7 on 2020-08-27 14:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0033_auto_20200827_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='tngproducts',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tngproducts',
            name='slug',
            field=models.SlugField(unique_for_date='date'),
        ),
    ]
