# Generated by Django 3.0.7 on 2020-08-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0035_auto_20200827_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tngproducts',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
