# Generated by Django 3.0.7 on 2020-08-27 18:56

from django.db import migrations, models
import prod.models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0036_auto_20200827_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tngproducts',
            name='slug',
            field=models.SlugField(default=prod.models.slug_unique_code, unique=True),
        ),
    ]
