# Generated by Django 3.0.7 on 2020-08-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0037_auto_20200828_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tngproducts',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
