# Generated by Django 3.0.7 on 2020-09-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0038_auto_20200828_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='tngproducts',
            name='model',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
