# Generated by Django 3.0.7 on 2020-09-26 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0041_auto_20200927_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tngproducts',
            name='color',
        ),
        migrations.AddField(
            model_name='colors',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prod.TngProducts'),
        ),
    ]
