# Generated by Django 3.0.7 on 2020-09-29 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0042_auto_20200927_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_colour',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_model',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
