# Generated by Django 3.0.7 on 2020-09-29 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0043_auto_20200929_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colors',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prod.TngProducts'),
        ),
        migrations.CreateModel(
            name='Product_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='product_pics')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prod.TngProducts')),
            ],
        ),
    ]
