# Generated by Django 3.0.7 on 2020-09-29 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0045_auto_20200929_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_model',
            name='image',
        ),
    ]
