# Generated by Django 3.0.7 on 2020-08-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shophome',
            old_name='heading',
            new_name='heading_1',
        ),
        migrations.AddField(
            model_name='shophome',
            name='heading_2',
            field=models.CharField(default='none', max_length=35),
        ),
    ]
