# Generated by Django 3.0.7 on 2020-08-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0002_auto_20200819_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shophome',
            name='heading_2',
            field=models.CharField(max_length=35),
        ),
    ]
