# Generated by Django 3.0.7 on 2020-08-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0004_shophome_linkname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shophome',
            name='linkname',
            field=models.CharField(max_length=20),
        ),
    ]
