# Generated by Django 3.0.7 on 2020-08-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0005_auto_20200819_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotDeals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='hotdeal.png', upload_to='product_pics')),
                ('days', models.PositiveIntegerField()),
                ('hours', models.PositiveIntegerField()),
                ('minutes', models.PositiveIntegerField()),
                ('seconds', models.PositiveIntegerField()),
                ('heading', models.CharField(max_length=70)),
                ('details', models.CharField(max_length=100)),
            ],
        ),
    ]
