# Generated by Django 3.0.7 on 2020-08-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0006_hotdeals'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotdeals',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
