# Generated by Django 3.0.7 on 2020-08-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0009_auto_20200821_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shophome',
            name='image',
            field=models.ImageField(upload_to='product_pics'),
        ),
    ]
