# Generated by Django 3.0.7 on 2020-09-01 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0038_auto_20200828_2309'),
        ('changes', '0012_topselling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topselling',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prod.TngProducts'),
        ),
    ]
