# Generated by Django 3.0.7 on 2020-09-01 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0013_auto_20200901_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topselling',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='changes.Category'),
        ),
    ]
