# Generated by Django 3.0.7 on 2020-09-02 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0039_tngproducts_model'),
        ('changes', '0014_auto_20200901_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelofProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_pics')),
                ('modelofproduct', models.ForeignKey(limit_choices_to={'type': 'model'}, on_delete=django.db.models.deletion.CASCADE, to='prod.TngProducts')),
            ],
        ),
    ]
