# Generated by Django 3.0.7 on 2020-09-02 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0039_tngproducts_model'),
        ('changes', '0017_auto_20200902_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelofproduct',
            name='modelofproduct',
            field=models.ForeignKey(limit_choices_to={'model': {'testing8', 'testing10', 'testing 1', 'waterproof-phone-bag', 'testing3', 'testing2', 'iphone-11', 'testing9', 'testing5', 'testing7', 'testing4', 'testing12', 'Testing6', 'testing11', 'iphonese', 'Type-C input and Type-C 18W'}}, on_delete=django.db.models.deletion.CASCADE, to='prod.TngProducts'),
        ),
    ]
