# Generated by Django 3.0.7 on 2020-09-02 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0039_tngproducts_model'),
        ('changes', '0018_auto_20200902_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelofproduct',
            name='modelofproduct',
            field=models.ForeignKey(limit_choices_to={'model': 'testing10,testing9'}, on_delete=django.db.models.deletion.CASCADE, to='prod.TngProducts'),
        ),
    ]
