# Generated by Django 3.0.7 on 2020-09-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0020_auto_20200902_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelofproduct',
            name='modelofproduct',
            field=models.CharField(max_length=100),
        ),
    ]
