# Generated by Django 3.0.7 on 2020-09-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0021_auto_20200902_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_pics')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
